application: officalupdater
version: 1
runtime: python
api_version: 1

handlers:
- url: /asset
  static_dir: asset

# "/", "/web", "/web/", "/web/other"
# (though the "other" part will be ignored by handlers),
# and alike will be routined to main.
# But "/webb" and alike will not.
- url: /($|web|desktop|mobile)
  script: main.py
  
# Bulk data load.
- url: /admin/import
  script: muloader.py
  login: admin
