application: officialupdater
version: 1
runtime: python
api_version: 1

handlers:
- url: /u/assets/
  static_dir: assets

- url: /admin/assets/
  static_dir: assets

- url: /assets/
  static_dir: assets

# Bulk data load.
- url: /admin/import
  script: muloader.py
  login: admin

- url: /(|u/.*)
  script: main.py
  
