application: microupdater
version: 1 
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: media/images/favicon.png
  upload: public/images/favicon.png

- url: /media
  static_dir: public

- url: /worker/.*
  script: sub.py

- url: /admin/croned
  script: croned.py
  login: admin

- url: /admin/test.*
  script: gaeunit.py
  login: admin

- url: /admin/remote
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /*
  script: main.py
  
