application: microupdater
version: 1
runtime: python
api_version: 1

handlers:
- url: /rpc_relay.html
  static_files: static/rpc_relay.html
  upload: static/rpc_relay.html 

- url: /canvas.html
  static_files: static/canvas.html
  upload: static/canvas.html

- url: /static
  static_dir: static

- url: /admin/croned
  script: croned.py
  login: admin

- url: /admin/remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /*
  script: main.py
  
